train_batch_size = 128
val_batch_size = 128

[dataset.specific]
name = "cifar"

[pl_module]
num_classes = 10

[pl_module.optim]
lr_list = [3e-4, 4e-4, 5e-4]
lr_milestones = [100, 150, 180]

[pl_module.net.specific]
name = "vit"
embed_dim = 256
hidden_dim = 512
num_heads = 8
num_layers = 6
patch_size = 4
num_channels = 3
num_patches = 64
num_classes = 10
dropout = 0.2
