train_batch_size = 768
val_batch_size = 768

[train_dataset.specific]
name = "imagenet"
mode = "train"
epoch_scale_factor = 10.0

[[val_datasets]]
[val_datasets.specific]
name = "imagenet"
mode = "val"
epoch_scale_factor = 1.0

[pl_module]
num_classes = 1000

[pl_module.optim]
lr_list = [3e-4, 4e-4, 5e-4]
lr_milestones = [100, 150, 180]

[pl_module.net.specific]
name = "vit"
embed_dim = 256
hidden_dim = 512
num_heads = 8
num_layers = 6
patch_size = 16
num_channels = 3
num_patches = 196
num_classes = 1000
dropout = 0.2
